apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: port

resources:
  - liquidator.yaml

commonLabels:
  release: port

configMapGenerator:
  - name: port-liquidator-config
    files:
      - ../config/liquidator.json
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: port-liquidator-secret
    envs:
      - $HOME/.config/solana/id
    literals:
      # - CLUSTER_URL=https://api.mainnet-beta.solana.com
      # - CLUSTER_URL=https://solana-api.projectserum.com
      - PROGRAM_ID=Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR
      - CHECK_INTERVAL=15000
      - CONFIG_FILE=/opt/port/liquidator.json
    options:
      disableNameSuffixHash: true