apiVersion: apps/v1
kind: Deployment
metadata:
  name: port-liquidator
  labels:
    app: port-liquidator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: port-liquidator
  template:
    metadata:
      labels:
        app: port-liquidator
    spec:
      containers:
        - name: port-liquidator
          image: 854153369854.dkr.ecr.ap-southeast-1.amazonaws.com/port-liquidator:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: port-liquidator-secret
          volumeMounts:
            - mountPath: /opt/port/
              name: liquidator-conf
      volumes:
        - name: liquidator-conf
          configMap:
            name: port-liquidator-config
